name = "RheaReactions"
uuid = "e7041bdd-cbf6-4fda-a9ae-fa15d3238eb4"
authors = ["St. Elmo Wilken <stelmozors@gmail.com> and contributors"]
version = "0.3.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[compat]
HTTP = "1.2"
JSON = "0.21"
Term = "1.0"
DocStringExtensions = "0.9"
julia = "1.7, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
